# -*- coding: utf-8 -*-
from odoo import models, fields, api, _


class AiAgent(models.Model):
    _name = 'ai_manager.agent'
    _description = 'AI Agent'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char(string='Name', required=True, tracking=True)
    description = fields.Text(string='Description', tracking=True)
    active = fields.Boolean(default=True)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('active', 'Active'),
        ('archived', 'Archived')
    ], string='Status', default='draft', required=True, tracking=True)

    llm_model = fields.Selection([
        ('gpt-4o', 'GPT-4o (OpenAI)'),
        ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'),
        ('gemini-2.5-pro', 'Gemini 2.5 Pro (Google)'),
        ('gemini-2.5-flash', 'Gemini 2.5 Flash (Google)'),
        ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'),
        ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)'),
        ('claude-3-5-sonnet', 'Claude 3.5 Sonnet (Anthropic)')
    ], string='LLM Model', default='gpt-4o', required=True, tracking=True)

    system_prompt = fields.Text(
        string='System Prompt',
        required=True,
        default="You are a helpful AI agent within Odoo.",
        tracking=True
    )

    color = fields.Integer("Color Index")

    tool_ids = fields.Many2many('ai_manager.tool', string='Tools / Capabilities')
    task_ids = fields.One2many('ai_manager.task', 'agent_id', string='Tasks / Triggers')
    log_ids = fields.One2many('ai_manager.log', 'agent_id', string='Execution Logs')

    success_count = fields.Integer(string="Successful Executions", compute='_compute_stats')
    fail_count = fields.Integer(string="Failed Executions", compute='_compute_stats')

    @api.depends('log_ids.state')
    def _compute_stats(self):
        for agent in self:
            agent.success_count = len(agent.log_ids.filtered(lambda l: l.state == 'success'))
            agent.fail_count = len(agent.log_ids.filtered(lambda l: l.state == 'failed'))

    def action_activate(self):
        for record in self:
            record.write({'state': 'active'})

    def action_draft(self):
        for record in self:
            record.write({'state': 'draft'})

    def action_archive(self):
        for record in self:
            record.write({'state': 'archived', 'active': False})

    def action_open_sandbox(self):
        self.ensure_one()
        # Allows to open a wizard or special view to chat with the agent
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Sandbox'),
                'message': _('Sandbox interface will be implemented here.'),
                'type': 'info',
                'sticky': False,
            }
        }

    def execute_action(self, record, action_code):
        """
        Executes the agent for a specific record context.
        The AI generates Odoo Python ORM code to fulfill the prompt, which is then executed safely.
        """
        self.ensure_one()
        from odoo.tools.safe_eval import safe_eval
        import re

        context_str = f"Trigger Record Model: {record._name}\nTrigger Record ID: {record.id}\nTrigger Record Name: {record.display_name}\n"
             
        system_instruction = (
            "You are an advanced Odoo Assistant Agent with execution capabilities. "
            "Based on the user's action code and context, you must write a Python script using the Odoo ORM to perform the desired action. "
            "CRITICAL ODOO SAFE_EVAL CONSTRAINTS:\n"
            "1. You CANNOT use 'import' statements (e.g., no 'import re', 'import time').\n"
            "2. You CANNOT mutate record attributes directly (e.g., do NOT use `record.active = False`). You MUST use the ORM `write` method instead (e.g., `record.write({'active': False})`).\n"
            "You have access to the following local variables:\n"
            "- `env`: the Odoo Environment (e.g. env['res.partner'])\n"
            "- `record`: the Odoo record that triggered this action. You can read its fields or call methods on it.\n\n"
            "Return ONLY valid Python code enclosed in a ```python ... ``` block. Do NOT provide explanations. Just the code."
        )
        
        prompt = f"Action to perform:\n{action_code}\n\nContext:\n{context_str}\n\n{system_instruction}"
        
        try:
            response_text, tokens = self._call_llm(prompt)
            state = 'success'
            
            # Extract Python code
            match = re.search(r'```python\n(.*?)\n```', response_text, re.DOTALL)
            if not match:
                # Fallback if the AI just wrote code without formatting
                code_to_execute = response_text.replace('```python', '').replace('```', '').strip()
            else:
                code_to_execute = match.group(1).strip()
                
            execution_log = "Python code generated by AI:\n" + code_to_execute
            
            # Execute the code safely
            eval_context = {
                'env': self.env,
                'record': record,
            }
            try:
                safe_eval(code_to_execute, eval_context, mode='exec')
                execution_log += "\n\n--- Execution: SUCCESS ---"
            except Exception as e:
                execution_log += f"\n\n--- Execution: FAILED ---\n{str(e)}"
                state = 'failed'
                
        except Exception as e:
            execution_log = f"LLM Connection Error: {str(e)}"
            tokens = 0
            state = 'failed'
            
        self.env['ai_manager.log'].create({
            'agent_id': self.id,
            'input_data': f"Automated Trigger for {record._name}({record.id}):\n{action_code}",
            'state': state,
            'output_data': execution_log,
            'cost_tokens': tokens
        })
        
        return state == 'success'

    def _call_llm(self, user_prompt):
        """
        Executes an HTTP request to the selected LLM provider.
        Returns a tuple: (response_text, tokens_used)
        """
        self.ensure_one()
        import requests
        import json
        from odoo.exceptions import UserError

        model = self.llm_model
        system_prompt = self.system_prompt or ""
        company = self.env.company

        if model.startswith('gpt'):
            api_key = company.ai_agent_openai_api_key
            if not api_key:
                raise UserError(_("Please configure your OpenAI API Key in Settings."))
            
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            }
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ]
            }
            try:
                response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=60)
                response.raise_for_status()
                data = response.json()
                return data['choices'][0]['message']['content'], data.get('usage', {}).get('total_tokens', 0)
            except Exception as e:
                raise UserError(_("OpenAI API Error: %s") % str(e))

        elif model.startswith('gemini'):
            api_key = company.ai_agent_gemini_api_key
            if not api_key:
                raise UserError(_("Please configure your Google Gemini API Key in Settings."))
            
            endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
            headers = {"Content-Type": "application/json"}
            payload = {
                "systemInstruction": {"parts": [{"text": system_prompt}]},
                "contents": [{"parts": [{"text": user_prompt}]}]
            }
            try:
                response = requests.post(endpoint, headers=headers, json=payload, timeout=60)
                response.raise_for_status()
                data = response.json()
                text = data['candidates'][0]['content']['parts'][0]['text']
                tokens = data.get('usageMetadata', {}).get('totalTokenCount', 0)
                return text, tokens
            except Exception as e:
                raise UserError(_("Gemini API Error: %s\nResponse: %s") % (str(e), response.text if 'response' in locals() else ''))

        elif model.startswith('claude'):
            api_key = company.ai_agent_claude_api_key
            if not api_key:
                raise UserError(_("Please configure your Anthropic Claude API Key in Settings."))
            
            # Map simplified names to Anthropic full model names if necessary
            anthropic_model = "claude-3-5-sonnet-20240620" if "sonnet" in model else "claude-3-5-haiku-20241022"
            
            headers = {
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json"
            }
            payload = {
                "model": anthropic_model,
                "system": system_prompt,
                "messages": [
                    {"role": "user", "content": user_prompt}
                ],
                "max_tokens": 4096
            }
            try:
                response = requests.post("https://api.anthropic.com/v1/messages", headers=headers, json=payload, timeout=60)
                response.raise_for_status()
                data = response.json()
                return data['content'][0]['text'], data.get('usage', {}).get('input_tokens', 0) + data.get('usage', {}).get('output_tokens', 0)
            except Exception as e:
                raise UserError(_("Anthropic API Error: %s\nResponse: %s") % (str(e), response.text if 'response' in locals() else ''))

        raise UserError(_("Unsupported LLM Model: %s") % model)
