# -*- coding: utf-8 -*-
from odoo import models, fields


class AiAgentLog(models.Model):
    _name = 'ai_manager.log'
    _description = 'AI Agent Execution Log'
    _order = 'create_date desc'

    agent_id = fields.Many2one('ai_manager.agent', string='Agent', required=True, ondelete='cascade')
    task_id = fields.Many2one('ai_manager.task', string='Trigger Task')

    input_data = fields.Text(string='Input / Context')
    output_data = fields.Text(string='Output / Response')
    
    state = fields.Selection([
        ('pending', 'Pending (Human Validation)'),
        ('success', 'Success'),
        ('failed', 'Failed')
    ], string='Status', default='success', required=True)

    cost_tokens = fields.Integer(string='Tokens Used', default=0)

    def action_validate(self):
        for log in self:
            if log.state == 'pending':
                # Execute the proposed action here
                log.write({'state': 'success'})

    def action_reject(self):
        for log in self:
            if log.state == 'pending':
                log.write({'state': 'failed', 'output_data': log.output_data + "\n\n[REJECTED BY HUMAN]"})

    def action_convert_to_automation(self):
        """ Transform the generated Python code into a production Odoo base.automation """
        for log in self:
            if log.state != 'success' or not log.output_data:
                continue
                
            # Extract code from output
            code_parts = log.output_data.split("Python code generated by AI:\n")
            if len(code_parts) < 2:
                continue
            code = code_parts[-1].split("\n\n--- Execution:")[0].strip()
            
            ir_model = self.env['ir.model'].search([('model', '=', 'res.partner')], limit=1)
            
            # Create server action
            action = self.env['ir.actions.server'].create({
                'name': f"[AI Generated] {log.task_id.name or log.agent_id.name}",
                'model_id': ir_model.id,
                'state': 'code',
                'code': code,
            })
            
            # Create base.automation (handle Odoo structure)
            automation_vals = {
                'name': f"[AI Generated] {log.task_id.name or log.agent_id.name}",
                'model_id': ir_model.id,
                'trigger': 'on_create',
            }
            if 'action_server_ids' in self.env['base.automation']._fields:
                automation_vals['action_server_ids'] = [(4, action.id)]
            elif 'action_server_id' in self.env['base.automation']._fields:
                automation_vals['action_server_id'] = action.id
            else:
                automation_vals['state'] = 'code'
                automation_vals['code'] = code

            automation = self.env['base.automation'].create(automation_vals)
            
            # Archive the agent and specific task to stop LLM calls
            log.agent_id.active = False
            if log.task_id:
                log.task_id.active = False
            
            # Notify User
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': 'Succès !',
                    'message': f"Action Automatisée '{automation.name}' créée avec succès. L'Agent IA original a été mis en pause.",
                    'type': 'success',
                    'sticky': False,
                    'next': {'type': 'ir.actions.act_window_close'},
                }
            }
